name: Java Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # пример «безопасного» шага
      - name: Collect Java files
        run: |
          if [ -d ./test ]; then
            find ./test -type f -name "*.java" > tests.txt
          else
            find ./src -type f -name "*.java" > tests.txt
          fi

      # …дальше оставь остальные шаги тестов как в оригинале
